name: Publish to Maven Central

on:
  workflow_call:
    inputs:
      type:
        description: "The type of publication"
        required: true
        type: string


jobs:
  publish:
    if: github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      - name: Build with Gradle
        # This just publishes to the local file system; jreleaser is responsible for uploading to maven central
        run: ./gradlew publish
      - name: Upload to Maven Central
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_TOKEN }}
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
          JRELEASER_NEXUS2_TOKEN: ${{ secrets.JRELEASER_NEXUS2_TOKEN }}
          # The content uploaded to maven central needs to be signed.  The public keys need to be published,
          # see https://central.sonatype.org/publish/requirements/gpg/#distributing-your-public-key for accepted
          # locations
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          # The content here needs to be the values of the public and secret key pair
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          # Overrides the configuration of 'NEVER'
          JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_RELEASE_DEPLOY_ACTIVE: "${{ (inputs.type == 'RELEASE' && inputs.type) || 'NEVER'  }}"
          JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_SNAPSHOT_DEPLOY_ACTIVE: "${{ (inputs.type == 'SNAPSHOT' && inputs.type) || 'NEVER'  }}"
        run: ./gradlew jreleaserDeploy
      - name: Store JReleaser Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser
          path: build/jreleaser
      - name: Store Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: build/reports
